django_liongram/accounts/urls.py
from django.urls import path, include
from .views import signup_view, login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

django_liongram/config/urls.py
from django.contrib import admin
from django.conf import settings # conf -> settings의 모든 값들을 가져올 수 있다.
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import url_view, url_parameter_view, function_view, class_view, function_list_view, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view), # int, str 둘다 사용 가능
    path('fbv/', function_view),
    path('fbv/list/', function_list_view),
    path('cbv/', class_view.as_view(), name='cbv'), #class -> .as_view()
    
    path('', index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')), # accounts의 url
    path('posts/', include('posts.urls', namespace='posts')), # post의 url
    
    
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # create한 이미지가 그냥 폴더 내부가 아닌 media 폴더 내에 넣기 위해서 media 폴더와 연결해준다(+=)

django_liongram/posts/urls.py
from django.urls import path
from .views import post_create_view, post_create_form_view, post_delete_view, post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    path('create/', post_create_form_view, name='post-create'), # form 전용 view 
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete', post_delete_view, name='post-delete'),
]

django_liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>{% block title %} {% endblock %} | 라이언그램</title>
</head>

<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <!-- 홈 버튼 생성-->
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icons/home_outlined_black_36dp.svg'%}" alt="홈">
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg'%}" alt="검색">
                </li>
                <li>
                    <a href="{% url 'posts:post-create' %}"> <!-- create로 이동 (post안의 url 의 name -> post-create)-->
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg'%}" alt="글쓰기">
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg'%}" alt="좋아요">
                </li>
                <li>
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg'%}" alt="프로필">
                </li>
            </ul>
        </nav>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
</body>

</html>

django_liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}홈{% endblock %}

{%block content %}
<main>
    <div class="card-list">
        {%for post in post_list%}
        {%include 'mixin/posts/post_card.html' with detail=False %} <!-- detail을 포함하기 위해-->
        {%endfor%}
    </div>
</main>
{% endblock %}