django_myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('lists/', include('list.urls')),
    path('contact/', include('contact.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('authaccounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_myproject/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views

urlpatterns = [
    path('', views.home, name='index'),
]

django_myproject/list/urls.py
from django.contrib import admin
from django.urls import path
from list import views
from .views import class_view

urlpatterns = [
    path('', views.listsHome, name='lists'),
    # path('create/', views.create, name='list-create'),
    path('create/', views.create_form, name='list-create'),
    path('<int:id>/', views.detail, name='list-detail'),
    # path('<int:id>/update/', views.update, name='list-update'),
    path('<int:id>/update/', views.update_form, name='list-update'),
    path('<int:id>/delete/', views.delete, name='list-delete'),
    # path('show/', class_view.as_view()),
    path('create_msg/<int:id>', views.create_msg, name='create_msg'),
    path('update_msg/<int:album_id>/<int:msg_id>', views.update_msg, name='update_msg'),
    path('delete_msg/<int:album_id>/<int:msg_id>', views.delete_msg, name='delete_msg'),
    
]

django_myproject/list/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class List(models.Model) :
    image = models.ImageField(verbose_name='앨범 이미지', null=True, blank=True) 
    title = models.CharField(verbose_name="앨범 제목", max_length=128)
    singer = models.CharField(verbose_name='가수 이름', max_length=128)
    content = models.TextField(verbose_name="내용", default="")
    created_at = models.DateField(verbose_name="출시일", auto_now_add=True)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자와 연결
    
    def __str__(self): 
        return self.title
    
class Message(models.Model) :
    content = models.CharField(verbose_name='응원글 내용', max_length=128)
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='List', on_delete=models.CASCADE) # fk 설정
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자와 연결
    
    def __str__(self): 
        return self.content

django_myproject/list/forms.py
from django import forms
from .models import List, Message

class PostModelForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['image', 'title', 'singer', 'content'] 
        
class MessageForm(forms.ModelForm):
    class Meta: 
        model = Message 
        fields = ['content']

django_myproject/list/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from .forms import PostModelForm, MessageForm
from django.views.generic import ListView
from django.core.paginator import Paginator

from .models import List, Message

# Create your views here.
def listsHome(request):
    object_list = List.objects.all().order_by('-created_at', '-id')
    paginator = Paginator(object_list, 4) # 4개씩 paginator
    pagnum = request.GET.get('page') # page 번호 get
    object_list = paginator.get_page(pagnum) # albums에 해당 페이지 번호에 해당하는 앨범들 저장 (갱신)
    return render(request, 'lists.html', {'object_list' : object_list})

@login_required
def create(request) : 
    if request.method == 'POST' or request.method == 'FILES':
        image = request.FILES.get('image')
        title = request.POST.get('title')
        singer = request.POST.get('singer')
        content = request.POST.get('content')
        List.objects.create (
            image=image,
            title=title,
            singer=singer,
            content=content,
            writer=request.user
        )
        return redirect('lists')
    else:
        return render(request, 'form_create.html')
    
def create_form(request) : 
    if request.method == 'POST' or request.method == 'FILES':
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid() :
            unfinished = form.save(commit=False)
            unfinished.writer = request.user
            unfinished.save()
            return redirect('lists')
    else:
        form = PostModelForm
        return render(request, 'form_create2.html', {'form' : form})
    

def detail(request, id) :
    try :
        album = List.objects.get(id=id)
        message_form = MessageForm()
        context = {
            'album' : album,
            'message_form' : message_form
        }
    except List.DoesNotExist :
        return redirect('lists')
    return render(request, 'list_detail.html', context)

@login_required
def update(request, id) :
    album = get_object_or_404(List, id=id, writer=request.user)
    
    if request.method == 'GET' :
        context = {'album' : album }
        return render(request, 'form_create.html', context)
    elif request.method == 'POST' :
        new_image = request.FILES.get('image')
        title = request.POST.get('title')
        singer = request.POST.get('singer')
        content = request.POST.get('content')
        
        if new_image :
            album.image.delete()
            album.image = new_image
        if title :
            album.title = title
        if singer :
            album.singer = singer 
        album.content = content
        album.save()
        return redirect('list-detail', album.id)

def update_form(request, id) : 
    album = get_object_or_404(List, id=id, writer=request.user)
    if request.method == 'POST' or request.method == 'FILES':
        form = PostModelForm(request.POST, request.FILES, instance=album)
        if form.is_valid() :
            form.save()
            return redirect('lists')
    else :
        form = PostModelForm(instance=album)
        context = {
            'form' : form,
            'id' : id
        }
        return render(request, 'form_create2.html', context)
    
@login_required
def delete(request, id) :
    album = get_object_or_404(List, id=id, writer=request.user)
    if request.method == 'GET' :
        context = {'album' : album}
        return render(request, 'delete_confirm.html', context)
    else :
        album.delete()
        return redirect('lists')

def create_msg(request, id) :
    filled_form = MessageForm(request.POST)

    if filled_form.is_valid():        
        finished_form = filled_form.save(commit=False)      
        finished_form.post = get_object_or_404(List, pk=id)    
        finished_form.writer = request.user    
        finished_form.save()   
    return redirect('list-detail', id)

def update_msg(request, album_id, msg_id) :
    msg = Message.objects.get(id=msg_id)
    msg_form = MessageForm(instance=msg) # msg에 들어가 있는 내용을 -> msg_form
    
    if request.method == 'POST' :
        update_form = MessageForm(request.POST, instance=msg) # post 요청이 오면 -> post와 함께 온 데이터를 update form 으로 저장
        if update_form.is_valid() :
            update_form.save()
            return redirect('list-detail', album_id)
    else : #GET
        return render(request, 'msg_update.html', {'msg_form' : msg_form})
        #GET 요청이라면 msg_update.html을 띄워주고, 그 템플릿에는 앞서 저장한 msg_form의 변수가 전달됩니다.

def delete_msg(request, album_id, msg_id) :
    msg = Message.objects.get(id=msg_id)
    msg.delete()
    
    return redirect('list-detail', album_id)


class class_view(ListView) :
    model = List # Post 기반 모델
    ordering = ['id'] # orderby랑 같은거
    template_name = 'show_list.html' # 출력 창
    
    

django_myproject/list/templates/delete_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block title %} delete album {% endblock %}
{% block css %}
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />
{% endblock%}

{% block content %}
<header class="py-5">
    <div class="container px-lg-5">
        <h1>ALBUM DELETE</h1>
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <form action="" method="POST"> {% csrf_token %}
                <p>Once deleted, data cannot be recovered.</p>
                <p>Do you still want to delete it?</p>
                <p>Album title to delete : {{ album.title }}</p>
                <a href="{% url 'lists' %}">RETURN</a>
                <input type="submit" value="DELETE">
            </form>
            <div>
                {% include 'list_card.html' %}
            </div>
        </div>
        <a href="{% url 'lists' %}">RETURN</a>
    </div>
</header>


{% endblock %}

django_myproject/list/templates/form_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} new album create {% endblock %}
{% block css %}
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />
{% endblock%}

{% block content %}
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-left">

            <h1>앨범을 추가하세요</h1>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <label for="id_image"><b>앨범 이미지 : </b></label>
                    {% if album.image %}
                    <p>현재 : <a href="{{ album.image.url }}">{{ album.image.name }}</a></p>
                    <p>변경 : <input type="file" name="image" accept="image/" id="id_image"></p>
                    {% else %}
                    <input type="file" name="image" accept="image/" id="id_image">
                    {% endif %}
                </div>

                <div>
                    <label for="id_title"><b>앨범 제목 : </b></label>
                    {% if album %}
                    <p>현재 : {{ album.title }} </p>
                    <p>변경 : <input type="text" name="title" id="id_title"></p>
                    {% else %}
                    <input type="text" name="title" id="id_title">
                    {% endif %}
                </div>

                <div>
                    <label for="id_singer"><b>앨범 가수 : </b></label>
                    {% if album %}
                    <p>현재 : {{ album.singer }} </p>
                    <p>변경 : <input type="text" name="singer" id="id_singer"></p>
                    {% else %}
                    <input type="text" name="singer" id="id_singer">
                    {% endif %}
                </div>

                <div>
                    <label for="id_content"><b>앨범 내용 : </b></label>
                    <textarea name="content" id="id_content" cols="30" rows="10">
                        {% if album %}
                        {{ album.content }}
                        {% endif %}
                    </textarea>
                </div>

                <br>
                <input type="submit">
            </form>

        </div>
    </div>
</header>
{% endblock %}

django_myproject/list/templates/form_create2.html
{% extends 'base.html' %}
{% load static %}

{% block title %} new album create _ form {% endblock %}
{% block css %}
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />
{% endblock%}

{% block content %}
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-left">

            <h1>ALBUM</h1>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {{ form.as_p }}
                </div>

                <br>
                <input type="submit">
            </form>

        </div>
    </div>
</header>
{% endblock %}

django_myproject/list/templates/list_card.html
{% load static %}

<div class="col mb-5">
    <div class="card h-100">
        {% if album.image %}
        {% if detail %}
        <div text-align="center">
            <img src="{{ album.image.url }}" height="500px" width="500px" />
        </div>
        {% else %}
        <img src="{{ album.image.url }}" class="card-img-top" />
        {% endif %}
        {% else %}
        <img src="http://via.placeholder.com/50x50" alt="" />
        {% endif %}

        <div class="card-body p-4">
            <div class="text-center">
                <h5 class="fw-bolder">{{ album.title }}</h2>
                    <p class="mb-0">
                        Singer : {{ album.singer }}
                    </p>
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    {% if detail %}
                    Content : {{ album.content }}
                    {% endif %}
                    <div>Writer : {{ album.writer }}</div>
            </div>
        </div>
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
                {% if not detail %}
                <a class="btn btn-outline-dark mt-auto" href="{% url 'list-detail' album.id %}">DETAIL</a>
                {% endif %}
            </div>
        </div>

        <div class="text-center">
            {% if request.user == album.writer %}
            <a href="{% url 'list-update' album.id %}">UPDATE</a> |
            <a href="{% url 'list-delete' album.id %}">DELETE</a>
            {% endif %}
        </div>
    </div>
</div>

django_myproject/list/templates/list_detail.html
{% extends 'base.html' %} {% load static %} {% block title %} detail {% endblock %} {% block css %}
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />
{% endblock%} {% block content %}
<header class="py-5">
    <div class="container px-lg-5">
        <h1>Album's Detail</h1>
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div>{% include 'list_card.html' with detail=True %}</div>
            <div>
                <h4>Comments</h4>
                {% if user.is_authenticated %}
                <form method="POST" action="{% url 'create_msg' album.id %}">
                    {% csrf_token %} {{ message_form }}
                    <input type="submit" />
                </form>
                <hr />
                {% for message in album.message_set.all %}
                <p>{{ message }}</p>
                <p>Writer : {{ message.writer }}</p>
                {% if request.user == message.writer %}
                <a href="{% url 'update_msg' album.id message.id %}">UPDATE</a>
                <a href="{% url 'delete_msg' album.id message.id %}">DELETE</a>
                {% endif %}
                <hr />
                {% endfor %} {% else %} Please log in and use it! {% endif %}
            </div>
        </div>
        <a href="{% url 'lists' %}">RETURN</a>
    </div>
</header>
{% endblock %}

django_myproject/list/templates/lists.html
{% extends 'base.html' %}
{% load static %}
{% block title %} album lists {% endblock %}
{% block css %}
<link href="{% static 'css/styles_shop.css' %}" rel="stylesheet" />
{% endblock%}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Album Lists</h1>
            <p class="fs-4">ADD NEW ALBUM</p>
            <a class="btn btn-primary btn-lg" href="{% url 'list-create' %}">create</a>
        </div>
    </div>
</header>
<!-- Page Content-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <!-- Page Features-->
            {% for album in object_list %}
            {% include 'list_card.html' with detail=False %}
            {% endfor %}
        </div>
        {% if object_list.has_previous %} <!-- 이전 페이지가 있다면 -->
        <a href="?page=1">첫 페이지</a>
        <a href="?page={{ object_list.previous_page_number }}">PREVIOUS</a>
        {% endif %}

        <span>{{ object_list.number }}</span> <!-- 현재 페이지 넘버-->
        <span> / </span>
        <span>{{ object_list.paginator.num_pages }}</span> <!-- 총 페이지 수-->

        {% if object_list.has_next %} <!-- 다음 페이지가 있다면 -->
        <a href="?page={{ object_list.next_page_number }}">NEXT</a>
        <a href="?page={{ object_list.paginator.num_pages }}">마지막 페이지</a>
        {% endif %}
    </div>
</section>


{% endblock %}

django_myproject/list/templates/msg_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %} msg update {% endblock %}
{% block css %}
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />
{% endblock%}

{% block content %}
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-left">

            <h1>message update</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <div>
                    {{ msg_form.as_p }}
                </div>

                <br>
                <input type="submit" value="UPDATE">
            </form>

        </div>
    </div>
</header>
{% endblock %}

django_myproject/list/templates/show_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>show lists</title>
</head>

<body>
    {% for object in object_list %}
    <p>제목 : {{ object.title }} / 가수 : {{ object.singer }}</p>
    {% endfor %}
</body>

</html>