django_liongram/config/urls.py
from django.contrib import admin
from django.conf import settings # conf -> settings의 모든 값들을 가져올 수 있다.
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import url_view, url_parameter_view, function_view, class_view, function_list_view, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view), # int, str 둘다 사용 가능
    path('fbv/', function_view),
    path('fbv/list/', function_list_view),
    path('cbv/', class_view.as_view(), name='cbv'), #class -> .as_view()
    
    path('', index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')), # accounts의 url
    path('posts/', include('posts.urls', namespace='posts')), # post의 url
    
    
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # create한 이미지가 그냥 폴더 내부가 아닌 media 폴더 내에 넣기 위해서 media 폴더와 연결해준다(+=)

django_liongram/posts/urls.py
from django.urls import path
from .views import post_create_view, post_create_form_view, post_delete_view, post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    path('create/', post_create_form_view, name='post-create'), # form 전용 view 
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete', post_delete_view, name='post-delete'),
]

django_liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model() # usermodel 

# 게시글 class
class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True) #verbose_name: 필드 이름 지정
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자와 연결
    
# 댓글 class    
class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE) # fk 설정
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True) # 사용자와 연결
    

django_liongram/posts/forms.py
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import Post

# class PostBaseForm(forms.Form) :
#     CATEGORY_CHOICES = [
#         ('1', '일반'),
#         ('2', '계정'),
#     ]
#     image = forms.ImageField(label='이미지') 
#     content = forms.CharField(label='내용', widget=forms.Textarea, required=True) # widget 지정 -> textarea 사용 
#     category = forms.ChoiceField(label='카테고리',choices=CATEGORY_CHOICES) # choice (category 생성)

# ModelForm 
class PostBaseForm(forms.ModelForm) :
    class Meta: 
        model = Post
        fields = '__all__'
        
from django.core.exceptions import ValidationError
class PostCreateForm(PostBaseForm) :
    class Meta(PostBaseForm.Meta) :
        fields = ['image' , 'content'] 
    
    # validation - custom ! 
    def clean_content(self) :
        data = self.cleaned_data['content']
        if "비속어" == data:
            raise ValidationError("비속어를 사용하실 수 없습니다.")
        return data
        
class PostUpdateForm(PostBaseForm) :
    class Meta(PostBaseForm.Meta) :
        fields = ['image' , 'content'] 
        
class PostDetailForm(PostBaseForm) :
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields :
            self.fields[key].widget.attrs['disabled'] = True
        

django_liongram/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView

from .models import Post 
from .forms import PostBaseForm, PostCreateForm, PostDetailForm

def index(request):
    post_list = Post.objects.all().order_by('-created_at') # post의 전체 데이터 조회  / 최신꺼 맨 위로 -> orderby
    context = {
        'post_list' : post_list,
    }
    return render(request, 'index.html', context) # context 같이 보내주기 !!

def post_list_view(request) :
    post_list = Post.objects.all() # post의 전체 데이터 조회 
    # post_list = Post.objects.filter(writer=request.user) #filter : Post.writer가 현재 로그인인 것 조회
    context = {
        'post_list' : post_list,
    }
    return render(request, 'posts/post_list.html', context) # context 같이 보내주기 !!

def post_detail_view(request, id) :
    # 없으면 redirect -> 예외 처리
    try : 
        post = Post.objects.get(id=id) # 하나만 불러오기 -> get
    except Post.DoesNotExist :
        return redirect('index')
    context = {
        'post': post,
        'form' : PostDetailForm(),
    }
    return render(request, 'posts/post_detail.html', context)

@login_required # 로그인이 필요하다 
def post_create_view(request) :
    # request.method 확인하기 !! get -> 폼 화면 표시 / post -> index 화면으로 redirect
    if request.method == 'GET' :
        return render(request, 'posts/post_form.html')
    else :
        image = request.FILES.get('image') # post_form.html -> image, content 가져오기
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create( # model에 새로운 데이터 생성
            image=image,
            content=content,
            writer=request.user # 로그인(admin에서) 안한 상태이면 실행 안됨 -> admin에서 로그인 되어있을때는 실행되고 잘 뜬다 
        )
        return redirect('index')
    
    
# form 전용 view
def post_create_form_view(request) :
    if request.method == 'GET' :
        form = PostCreateForm()
        return render(request, 'posts/post_form2.html', {'form' : form})
    else :
        form = PostCreateForm(request.POST , request.FILES)
        print(form)
        
        if form.is_valid() : # 폼이 유효한지 먼저 검사 / 그 후에 데이터 유효성 검사
            Post.objects.create( 
                image=form.cleaned_data['image'], # cleaned data : 유효성 검사를 해줌 -> 단, form이 유효한지 검사부터 해야지 에러가 안남
                content=form.cleaned_data['content'],
                writer=request.user 
            )
        else : 
            return redirect('posts:post-create')
        return redirect('index')




@login_required # 작성자만 가능한 행위 - 로그인 필수 
def post_update_view(request, id) :
    #post = Post.objects.get(id=id) # 없는 id 로 들어갔을 때  아에 에러가 발생함
    post = get_object_or_404(Post, id=id, writer=request.user) 
    # writer=request.user 이어야 가능/ 아니면 404
    # 없는 id 로 들어갔을 때 에러 대신 404를 발생시킴 (윗 줄과 비교!!) -> 더 안전 ! 
    
    if request.method == 'GET' : # 수정하려고 수정하기에 접속했을 때 ! 
        context = { 'post': post }   
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST' : # new image 가져오기  -> 수정을 보냈을 때 ! 
        new_image = request.FILES.get('image') # post_form.html -> image, content 가져오기
        content = request.POST.get('content')
        print(new_image)
        print(content)
        
        # 새로운 이미지가 있을 때만, 변경 해주는 과정 !!  -> 같은 이미지가 계속 추가되는 것을 방지
        if new_image : 
            post.image.delete() # 새로운 이미지를 추가하기 전에 기존 이미지를 삭제
            post.image = new_image # 이미지 수정
        
        post.content = content # 내용 수정
        post.save() # 저장 
        return redirect('posts:post-detail', post.id) # 디테일 화면으로 리다이렉트 

# 작성자만 가능한 행위 - 로그인 필수
@login_required
def post_delete_view(request, id) :
    # user != writer -> return 404 -> 확인하는 것 
    post = get_object_or_404(Post, id=id, writer=request.user) # writer=request.user 이어야 가능/ 아니면 404
    
    # 윗줄 다른 방법 !
    # if request.user != post.writer : 
    #     raise Http404('잘못된 접근입니다.') 
    
    if request.method == 'GET' :
        context = {'post' : post}
        return render(request, 'posts/post_confirm_delete.html', context)
    else :
        post.delete() # 삭제 
        return redirect('index')








def url_view(request):
    print('url_view()')
    data = {'code' : '001', 'msg' : 'OK'}
    return HttpResponse('<h1>url_view</h1>') # text -> html로 작동함
    # return JsonResponse(data) # dictionary 형태 반환 -> json 으로 반환
    
# url에 변수 정해놓은거 함수 매개변수로 넣어주기 - username
def url_parameter_view(request, username) :
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET : {request.GET}') # queryString 받기
    return HttpResponse(username)

#form 입력 
def function_view(request) :
    print(f'request.method: {request.method}')
    
    # get 일땐 get 만 출력 , post일 떈 post 만 출력
    if request.method == 'GET' :
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST' :
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

#ListView 상속 받기
class class_view(ListView) :
    model = Post # Post 기반 모델
    #ordering = ['-id'] # orderby랑 같은거
    template_name = 'cbv_view.html' # 출력 창
    
# class_view 클래스를 함수로 구현한다면!!   
def function_list_view(request) :
    object_list = Post.objects.all().order_by('-id')
    return render(request, 'cbv_view.html', {'object_list' : object_list})

django_liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img src="http://via.placeholder.com/32x32" alt="프로필이미지" />
        <!-- 공백 이미지 링크-->
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
        <!-- 수정 폼 작성 할 것 -> 대신 작성자가 user일때만 가능 ! if-else -->
        {% if request.user == post.writer %}
        <a href="{% url 'posts:post-update' post.id%}">수정하기</a> |
        <a href="{% url 'posts:post-delete' post.id%}">삭제하기</a>
        {% endif %}
    </div>

    <div class="card__body">
        <div>
            {% if post.image %}
            <img class="card__image" src="{{ post.image.url }}" alt="" />
            {% else %}
            <img class="card__image" src="http://via.placeholder.com/600x600" alt="" />
            {% endif %}
        </div>

        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요" />
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글" />
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기" />
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크" />
            </div>
        </div>

    </div>

    <div class="card_content">
        <span class="card__like-num">좋아요 00개</span>
        <div class="card__main-text">
            <p>
                <span class="card__user-name">{{ post.writer }}</span>
                {% if not detail %}
                {{ post.content|truncatechars:35 }}
                {% else %}
                {{post.content}}
                {% endif %}
            </p>
            {% if not detail %} <!-- post_detail.html : with detail=True -->
            <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
            <!-- /posts/{{post.id}}-->
            {% endif %}
        </div>
        <div>
            <p>댓글 {{ post.comment_set.all.count }}개 <!-- post에서 comment 역참조-->
                {% if not detail %} <!-- post_detail.html : with detail=True -->
                <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                {% endif %}
            </p>
            <ul class="card__comment-group">
                {% if not detail %}
                {% for comment in post.comment_set.all|slice:":2" %} <!-- 댓글 2개로 slicing-->
                <li>
                    <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                </li>
                {% endfor %}
                {% else %}
                {% for comment in post.comment_set.all %}
                <li>
                    <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                </li>
                {% endfor %}
                {% endif %}
            </ul>
            <p class="card__created-at">{{ post.created_at|date:"Y년 m월 d일"}}</p>
        </div>
    </div>
</div>